#!/usr/bin/env python3
"""Validate a compiled-music catalog and emit its bounded SNES lookup table."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import re

from same.music import CompiledMusicCatalog


def tad_songs(text: str) -> dict[str, int]:
    songs = {
        name: int(identifier)
        for name, identifier in re.findall(
            r"^\s*!Song_([A-Za-z0-9_]+)\s*=\s*(\d+)\s*(?:;.*)?$",
            text,
            re.MULTILINE,
        )
    }
    if not songs or len(set(songs.values())) != len(songs):
        raise RuntimeError("TAD song enum map is absent or duplicated")
    return songs


def generate(catalog_path: Path, enums_path: Path, output: Path, exclude_songs: set[str] | None = None) -> CompiledMusicCatalog:
    raw = catalog_path.read_bytes()
    if exclude_songs:
        document = json.loads(raw)
        document["entries"] = [
            entry for entry in document.get("entries", [])
            if entry.get("compiled_song") not in exclude_songs
        ]
        valid_route_ids = {
            (entry.get("logical_id"), entry.get("route", {}).get("kind"),
             entry.get("route", {}).get("value"))
            for entry in document["entries"] if entry.get("route")
        }
        document["sections"] = [
            section for section in document.get("sections", [])
            if (section.get("logical_id"), "hook", section.get("hook_value"))
            in valid_route_ids
        ]
        raw = json.dumps(document, separators=(",", ":")).encode()
    catalog = CompiledMusicCatalog.decode(
        raw, str(catalog_path), compiled_songs=tad_songs(enums_path.read_text(encoding="utf-8")),
    )
    if any(entry.logical_id > 255 for entry in catalog.entries):
        raise RuntimeError("SNES compiled-music logical IDs must fit in one byte")
    if any(entry.route_value > 255 for entry in catalog.entries):
        raise RuntimeError("SNES compiled-music route values must fit in one byte")
    default_entries = [
        entry for entry in catalog.entries
        if entry.route_kind == "default" and entry.route_value == 0
    ]
    pairs = ", ".join(
        f"${entry.logical_id:02X}, ${entry.compiled_song_id:02X}"
        for entry in default_entries
    )
    routed = [entry for entry in catalog.entries if entry.route_identity is not None]
    route_bytes = ", ".join(
        f"${entry.logical_id:02X}, ${1 if entry.route_kind == 'hook' else 0:02X}, "
        f"${entry.route_value:02X}, ${entry.compiled_song_id:02X}"
        for entry in routed
    )
    text = (
        "; Generated by tools/generate_music_catalog.py. Do not hand-edit.\n"
        f"; Catalog SHA-256: {hashlib.sha256(raw).hexdigest()}\n"
        f"SAME_MUSIC_CATALOG_COUNT = ${len(default_entries):02X}\n"
        "Same_Music_Catalog:\n"
        f"    .byte {pairs}\n"
        "Same_Music_Catalog_End:\n"
        f"SAME_MUSIC_ROUTE_COUNT = ${len(routed):02X}\n"
        "Same_Music_Routes:\n"
        + (f"    .byte {route_bytes}\n" if routed else "")
        + "Same_Music_Routes_End:\n"
    )
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(text, encoding="utf-8", newline="\n")
    return catalog


def generate_lifecycle(catalog: CompiledMusicCatalog, output: Path) -> None:
    """Emit optional runtime metadata separately from the stable lookup table."""
    durations = [
        0 if entry.loop_start is not None
        else entry.duration_frames(60, catalog.time_scale)
        for entry in catalog.entries
    ]
    if any(duration > 0xFFFF for duration in durations):
        raise RuntimeError("SNES music lifecycle duration exceeds 65535 frames")
    logical_ids = ", ".join(f"${entry.logical_id:02X}" for entry in catalog.entries)
    compiled_ids = ", ".join(
        f"${entry.compiled_song_id:02X}" for entry in catalog.entries
    )
    duration_words = ", ".join(f"${duration:04X}" for duration in durations)
    loop_flags = ", ".join(
        "$01" if entry.loop_start is not None else "$00" for entry in catalog.entries
    )
    text = (
        "; Generated by tools/generate_music_catalog.py. Do not hand-edit.\n"
        f"SAME_MUSIC_LIFECYCLE_COUNT = ${len(catalog.entries):02X}\n"
        "Same_Music_Lifecycle_LogicalIds:\n"
        f"    .byte {logical_ids}\n"
        "Same_Music_Lifecycle_CompiledIds:\n"
        f"    .byte {compiled_ids}\n"
        "Same_Music_Lifecycle_DurationFrames:\n"
        f"    .word {duration_words}\n"
        "Same_Music_Lifecycle_LoopFlags:\n"
        f"    .byte {loop_flags}\n"
    )
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(text, encoding="utf-8", newline="\n")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("catalog", type=Path)
    parser.add_argument("enums", type=Path)
    parser.add_argument("output", type=Path)
    parser.add_argument("--lifecycle-output", type=Path)
    parser.add_argument("--exclude-compiled-song", action="append", default=[])
    args = parser.parse_args()
    catalog = generate(args.catalog, args.enums, args.output, set(args.exclude_compiled_song))
    if args.lifecycle_output is not None:
        generate_lifecycle(catalog, args.lifecycle_output)
    print(f"{args.output} ({len(catalog.entries)} compiled music entries)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
