#!/usr/bin/env python3
"""Generate the independently selected production video-overlay seam."""

from __future__ import annotations

import argparse, json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def generate(name: str, carrier: str, backend: str, output: Path, manifest: Path) -> dict[str, object]:
    config = json.loads((ROOT / "runtime/snes/video_overlays.json").read_text())
    record = config["overlays"].get(name)
    if record is None: raise ValueError(f"unknown SNES video overlay {name!r}")
    if record["required_carrier"] not in (None, carrier): raise ValueError(f"video overlay {name} requires carrier {record['required_carrier']}")
    if record["required_backend"] not in (None, backend): raise ValueError(f"video overlay {name} requires backend {record['required_backend']}")
    output.mkdir(parents=True, exist_ok=True)
    enabled = name == "bg2_index4"
    lines = ["; Generated by tools/generate_snes_video_overlay.py. Do not hand-edit.",
             f"SAME_VIDEO_OVERLAY_ID = ${record['id']:02X}", f"SAME_VIDEO_OVERLAY_BG2 = ${int(enabled):02X}"]
    layout = None
    if enabled:
        layout = json.loads((ROOT / record["layout"]).read_text())
        expected = [("descriptor",0x41F000,32),("pixels",0x41F020,640),("tile_stage",0x41F2A0,704),("reserved",0x41F560,44),("active_cells",0x41F58C,44),("pending_cells",0x41F5B8,44),("inflight",0x41F5E4,48),("work",0x41F614,492),("tilemap_stage",0x41F800,2048)]
        end=0x41F000
        for key,address,size in expected:
            item=layout[key]; actual=int(item["address"].replace(":",""),16)
            if (actual,item["bytes"]) != (address,size) or actual < end: raise ValueError(f"invalid overlay region {key}")
            end=actual+size; lines += [f"SAME_OVERLAY_{key.upper()} = ${address:06X}",f"SAME_OVERLAY_{key.upper()}_SIZE = ${size:04X}"]
            if key in ("pixels", "tile_stage"):
                lines += [f"SAME_OVERLAY_{key.upper()}_LO = ${address & 0xFFFF:04X}"]
        if end != 0x420000: raise ValueError("overlay layout does not fill reserved staging")
        (output / "video_overlay_bg2_tilemap.bin").write_bytes(
            (b"\x40\x00" * 1024)
        )
        lines += ["SAME_OVERLAY_MAX_WIDTH = $0050","SAME_OVERLAY_MAX_HEIGHT = $0008","SAME_OVERLAY_MAX_CELLS = $0016","SAME_OVERLAY_BLANK_TILE = $0040","SAME_OVERLAY_FIRST_TILE = $0041","SAME_OVERLAY_LAST_TILE = $00BF"]
        lines += [
            "SAME_OVERLAY_DESCRIPTOR_MAGIC = SAME_OVERLAY_DESCRIPTOR+$00",
            "SAME_OVERLAY_DESCRIPTOR_SCHEMA = SAME_OVERLAY_DESCRIPTOR+$02",
            "SAME_OVERLAY_DESCRIPTOR_VISIBLE = SAME_OVERLAY_DESCRIPTOR+$03",
            "SAME_OVERLAY_DESCRIPTOR_GENERATION = SAME_OVERLAY_DESCRIPTOR+$04",
            "SAME_OVERLAY_DESCRIPTOR_X = SAME_OVERLAY_DESCRIPTOR+$08",
            "SAME_OVERLAY_DESCRIPTOR_Y = SAME_OVERLAY_DESCRIPTOR+$0A",
            "SAME_OVERLAY_DESCRIPTOR_WIDTH = SAME_OVERLAY_DESCRIPTOR+$0C",
            "SAME_OVERLAY_DESCRIPTOR_HEIGHT = SAME_OVERLAY_DESCRIPTOR+$0E",
            "SAME_OVERLAY_DESCRIPTOR_PITCH = SAME_OVERLAY_DESCRIPTOR+$10",
            "SAME_OVERLAY_DESCRIPTOR_TRANSPARENT = SAME_OVERLAY_DESCRIPTOR+$12",
            "SAME_OVERLAY_DESCRIPTOR_LENGTH = SAME_OVERLAY_DESCRIPTOR+$14",
            "SAME_OVERLAY_DESCRIPTOR_CONTENT_X0 = SAME_OVERLAY_DESCRIPTOR+$18",
            "SAME_OVERLAY_DESCRIPTOR_CONTENT_Y0 = SAME_OVERLAY_DESCRIPTOR+$1A",
            "SAME_OVERLAY_DESCRIPTOR_CONTENT_X1 = SAME_OVERLAY_DESCRIPTOR+$1C",
            "SAME_OVERLAY_DESCRIPTOR_CONTENT_Y1 = SAME_OVERLAY_DESCRIPTOR+$1E",
            "SAME_OVERLAY_STATE = SAME_OVERLAY_WORK+$00",
            "SAME_OVERLAY_CURRENT_GENERATION = SAME_OVERLAY_WORK+$02",
            "SAME_OVERLAY_COMMITTED_GENERATION = SAME_OVERLAY_WORK+$06",
            "SAME_OVERLAY_ACTIVE_COUNT = SAME_OVERLAY_WORK+$0A",
            "SAME_OVERLAY_PENDING = SAME_OVERLAY_WORK+$0B",
            "SAME_OVERLAY_INFLIGHT_COUNT = SAME_OVERLAY_WORK+$0C",
            "SAME_OVERLAY_ACCEPTED_COUNT = SAME_OVERLAY_WORK+$0E",
            "SAME_OVERLAY_REJECTED_COUNT = SAME_OVERLAY_WORK+$10",
            "SAME_OVERLAY_ERROR_COUNT = SAME_OVERLAY_WORK+$12",
            "SAME_OVERLAY_QUEUED_BYTES = SAME_OVERLAY_WORK+$14",
            "SAME_OVERLAY_EXPECTED_DMA = SAME_OVERLAY_WORK+$16",
            "SAME_OVERLAY_NEXT_GENERATION = SAME_OVERLAY_WORK+$18",
            "SAME_OVERLAY_VISUAL_UNAVAILABLE = SAME_OVERLAY_WORK+$1C",
            "; Phase 6G-B latency evidence: u16 SAME_FRAME_COUNTER snapshots.",
            "SAME_OVERLAY_TRACE_S0 = SAME_OVERLAY_WORK+$B2",
            "SAME_OVERLAY_TRACE_S1 = SAME_OVERLAY_WORK+$B4",
            "SAME_OVERLAY_TRACE_S2 = SAME_OVERLAY_WORK+$B6",
            "SAME_OVERLAY_TRACE_S3 = SAME_OVERLAY_WORK+$B8",
            "SAME_OVERLAY_TRACE_S4 = SAME_OVERLAY_WORK+$BA",
            "SAME_OVERLAY_TRACE_S5 = SAME_OVERLAY_WORK+$BC",
            "SAME_OVERLAY_TRACE_S6 = SAME_OVERLAY_WORK+$BE",
            "SAME_OVERLAY_TRACE_S7 = SAME_OVERLAY_WORK+$C0",
            "SAME_OVERLAY_TRACE_S8 = SAME_OVERLAY_WORK+$C2",
            "SAME_OVERLAY_TRACE_S9 = SAME_OVERLAY_WORK+$C4",
            "SAME_OVERLAY_TRACE_S11 = SAME_OVERLAY_WORK+$C6",
            "; Entry/exit evidence for the bounded backend preparation stages.",
            "SAME_OVERLAY_TRACE_S6_ENTRY = SAME_OVERLAY_WORK+$C8",
            "SAME_OVERLAY_TRACE_S6_EXIT = SAME_OVERLAY_WORK+$CA",
            "SAME_OVERLAY_TRACE_S7_ENTRY = SAME_OVERLAY_WORK+$CC",
            "SAME_OVERLAY_TRACE_S7_EXIT = SAME_OVERLAY_WORK+$CE",
            "SAME_OVERLAY_TRACE_S8_ENTRY = SAME_OVERLAY_WORK+$D0",
            "SAME_OVERLAY_TRACE_S8_EXIT = SAME_OVERLAY_WORK+$D2",
            "SAME_OVERLAY_TRACE_S9_ENTRY = SAME_OVERLAY_WORK+$D4",
            "SAME_OVERLAY_TRACE_S9_EXIT = SAME_OVERLAY_WORK+$D6",
            "SAME_OVERLAY_TRACE_NMI_ENTRY = SAME_OVERLAY_WORK+$D8",
            "SAME_OVERLAY_TRACE_NMI_EXIT = SAME_OVERLAY_WORK+$DA",
            "SAME_OVERLAY_MAGIC = $564F",
            "SAME_OVERLAY_SCHEMA = $01",
            "SAME_OVERLAY_STATE_IDLE = $00",
            "SAME_OVERLAY_STATE_PREPARING = $01",
            "SAME_OVERLAY_STATE_WAITING_DMA = $02",
            "SAME_OVERLAY_STATE_ERROR = $FF",
        ]
    else:
        for key in ("DESCRIPTOR","PIXELS","TILE_STAGE","TILEMAP_STAGE","ACTIVE_CELLS","PENDING_CELLS","INFLIGHT","WORK"):
            lines += [f"SAME_OVERLAY_{key} = $000000",f"SAME_OVERLAY_{key}_SIZE = $0000"]
    (output/"video_overlay_constants.inc.pasm").write_text("\n".join(lines)+"\n")
    hooks={"boot":"","reset":"","frame":"","service":"","commit":"","code":""}
    if enabled:
        hooks={
            "boot":"    jsl Same_Overlay_Bg2_Boot_Far\n",
            "reset":"    jsl Same_Overlay_Bg2_Reset_Far\n",
            "frame":"    jsl Same_Overlay_Bg2_Step_Far\n",
            "service":(
                "    jsl Same_Overlay_Bg2_Handle_Far\n"
                "    bcc Same_Video_Handle__overlay_not_handled\n"
                "    plp\n"
                "    rts\n"
                # Non-overlay video packets must fall through untouched to
                # the selected backend service.  The old generated fallback
                # treated the packet opcode as an overlay state/error, which
                # stranded room-surface dirty/palette/present packets before
                # the Mode-3 backend could consume them.
                "Same_Video_Handle__overlay_not_handled:\n"
            ),
            "commit":"    jsl Same_Overlay_Bg2_Commit_Far\n",
            "code":'.include "../services/video_overlay_bg2.pasm"\n',
        }
    for hook,body in hooks.items(): (output/f"video_overlay_{hook}.inc.pasm").write_text("; Generated video overlay hook.\n"+body)
    result={"format":"same-snes-video-overlay-manifest","version":1,"overlay":name,"overlay_id":record["id"],"default_overlay":config["default"],"carrier":carrier,"backend":backend,"layout":layout}
    manifest.write_text(json.dumps(result,indent=2,sort_keys=True)+"\n"); return result


def main() -> int:
    p=argparse.ArgumentParser();p.add_argument("--overlay",choices=("none","bg2_index4"),required=True);p.add_argument("--carrier",required=True);p.add_argument("--backend",required=True);p.add_argument("--output-dir",type=Path,default=ROOT/"runtime/snes/generated");p.add_argument("--manifest",type=Path,required=True);a=p.parse_args();print(json.dumps(generate(a.overlay,a.carrier,a.backend,a.output_dir,a.manifest),sort_keys=True));return 0
if __name__ == "__main__": raise SystemExit(main())
