#!/usr/bin/env python3
"""Generate bank-safe SNES delivery for cooked linear room visuals."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

from same.engines.scumm_v5.room_visual import decode_room_visual


def sha(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def byte_rows(data: bytes) -> str:
    return "\n".join(
        "    .byte " + ",".join(f"${value:02X}" for value in data[i:i + 16])
        for i in range(0, len(data), 16)
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--manifest", type=Path, action="append", required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--binary-dir", type=Path, required=True)
    parser.add_argument("--report", type=Path, required=True)
    parser.add_argument("--first-bank", type=lambda x: int(x, 0), default=16)
    parser.add_argument("--room", type=int, action="append", dest="rooms",
                        help="emit only this room from the supplied manifest (repeatable)")
    args = parser.parse_args()
    visuals = []
    for manifest_path in args.manifest:
        manifest = json.loads(manifest_path.read_text())
        for record in manifest.get("records", []):
            spec = record.get("visual")
            if spec is None:
                continue
            if args.rooms is not None and int(record["room"]) not in args.rooms:
                continue
            raw = (manifest_path.parent / spec["output"]).read_bytes()
            visual = decode_room_visual(raw, expected_room=int(record["room"]))
            if sha(raw) != spec["record_sha256"]:
                raise RuntimeError(f"{manifest_path}: visual record hash differs")
            visuals.append((visual, raw, spec, manifest_path))
    if not visuals:
        raise RuntimeError("no cooked room visual records were supplied")
    if len({item[0].room for item in visuals}) != len(visuals):
        raise RuntimeError("duplicate cooked room visual identity")
    args.binary_dir.mkdir(parents=True, exist_ok=True)
    lines = [
        "; Generated by tools/generate_snes_room_visuals.py.",
        f"SCUMM_V5_ROOM_VISUAL_COUNT = ${len(visuals):02X}",
        f"SCUMM_V5_INITIAL_VISUAL_ROOM = ${visuals[0][0].room:02X}",
        "SCUMM_V5_ROOM_VISUAL_DESCRIPTOR_MAGIC = $5652",
        "SCUMM_V5_ROOM_VISUAL_DESCRIPTOR_VERSION = $01",
    ]
    report_records = []
    bank = args.first_bank
    emitted = []
    for index, (visual, raw, spec, manifest_path) in enumerate(visuals):
        row_pointers = []
        row = 0
        segment = 0
        while row < visual.height:
            rows_fit = 0x8000 // visual.pitch
            count = min(rows_fit, visual.height - row)
            payload = visual.pixels[row * visual.pitch:(row + count) * visual.pitch]
            binary = args.binary_dir / f"visual-{index}-rows-{row}-{row + count - 1}.bin"
            binary.write_bytes(payload)
            label = f"ScummV5_RoomVisual_{index}_Rows_{segment}"
            lines.extend((f".bank {bank}", ".org $8000", f"{label}:",
                          f'    .incbin "{binary.resolve()}"'))
            for local in range(count):
                row_pointers.append((0x8000 + local * visual.pitch, bank))
            emitted.append({"bank": bank, "address": "8000", "bytes": len(payload),
                            "sha256": sha(payload), "rows": [row, row + count - 1]})
            row += count
            segment += 1
            bank += 1
        report_records.append({
            "room": visual.room, "width": visual.width, "height": visual.height,
            "pitch": visual.pitch, "record_sha256": visual.record_sha256,
            "decoded_pixels_sha256": visual.decoded_pixels_sha256,
            "decoded_palette_sha256": visual.decoded_palette_sha256,
            "source_manifest": str(manifest_path.resolve()),
            "row_pointers": row_pointers,
        })
    metadata_bank = bank
    lines.extend((
        f"SCUMM_V5_ROOM_VISUAL_FIRST_DATA_BANK = ${args.first_bank:02X}",
        f"SCUMM_V5_ROOM_VISUAL_LAST_DATA_BANK = ${metadata_bank - 1:02X}",
        f"SCUMM_V5_ROOM_VISUAL_DIRECTORY = ${metadata_bank:02X}8000",
        f".bank {metadata_bank}", ".org $8000", "ScummV5_RoomVisual_Directory:",
    ))
    metadata_cursor = 0x8000 + len(visuals) * 22
    metadata_locations = []
    for visual, raw, spec, manifest_path in visuals:
        palette_address = metadata_cursor
        metadata_cursor += 768
        rows_address = metadata_cursor
        metadata_cursor += visual.height * 5
        metadata_locations.append((palette_address, rows_address))
    if metadata_cursor > 0x10000:
        raise RuntimeError("room visual metadata does not fit one LoROM bank")
    for index, (visual, raw, spec, manifest_path) in enumerate(visuals):
        palette_address, rows_address = metadata_locations[index]
        lines.extend((
            f"    .byte ${visual.room:02X}",
            "    .word SCUMM_V5_ROOM_VISUAL_DESCRIPTOR_MAGIC",
            "    .byte SCUMM_V5_ROOM_VISUAL_DESCRIPTOR_VERSION,$01,$01",
            f"    .word ${visual.width:04X},${visual.height:04X},${visual.pitch:04X}",
            f"    .byte ${palette_address & 0xff:02X},${palette_address >> 8:02X},${metadata_bank:02X}",
            f"    .byte ${rows_address & 0xff:02X},${rows_address >> 8:02X},${metadata_bank:02X}",
            f"    .word ${visual.height:04X},$0300",
        ))
    for index, (visual, raw, spec, manifest_path) in enumerate(visuals):
        lines.extend((f"ScummV5_RoomVisual_{index}_Palette:", byte_rows(visual.palette),
                      f"ScummV5_RoomVisual_{index}_Rows:"))
        for address, row_bank in report_records[index]["row_pointers"]:
            lines.append(
                f"    .byte ${address & 0xff:02X},${address >> 8:02X},${row_bank:02X}"
                f"\n    .word ${visual.pitch:04X}"
            )
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(lines) + "\n")
    report = {
        "schema": "same_snes_room_visual_delivery_v1", "first_bank": args.first_bank,
        "metadata_bank": metadata_bank, "records": report_records, "emitted": emitted,
    }
    args.report.parent.mkdir(parents=True, exist_ok=True)
    args.report.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n")
    print(json.dumps({"output": str(args.output), "report": str(args.report),
                      "records": len(visuals), "last_bank": metadata_bank}, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
