#!/usr/bin/env python3
"""Generate the Poppy constants for the compiled Fate TAD data blob."""

from __future__ import annotations

import argparse
from pathlib import Path
import re


LOADER_SIZE = 116
DEFAULT_DRIVER_SIZE = 3218
ASAR_LOROM_BIAS = 51
LOROM_BANK_BYTES = 0x8000


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("binary", type=Path)
    parser.add_argument("enums", type=Path)
    parser.add_argument("output", type=Path)
    parser.add_argument("--assembly", type=Path)
    args = parser.parse_args()

    data = args.binary.read_bytes()
    enum_text = args.enums.read_text(encoding="utf-8")
    driver_size = DEFAULT_DRIVER_SIZE
    if args.assembly is not None:
        assembly = args.assembly.read_text(encoding="utf-8")
        driver_match = re.search(r"^Tad_AudioDriver_SIZE\s*=\s*(\d+)\s*$", assembly, re.MULTILINE)
        if driver_match is None:
            raise SystemExit("TAD assembly has no audio-driver size")
        driver_size = int(driver_match.group(1))
    data_table_offset = LOADER_SIZE + driver_size
    match = re.search(r"^!LAST_SONG_ID\s*=\s*(\d+)\s*$", enum_text, re.MULTILINE)
    if match is None:
        raise SystemExit("TAD enum file has no LAST_SONG_ID")
    last_song = int(match.group(1))
    songs = {
        name: int(identifier)
        for name, identifier in re.findall(
            r"^\s*!Song_([A-Za-z0-9_]+)\s*=\s*(\d+)\s*(?:;.*)?$",
            enum_text,
            re.MULTILINE,
        )
    }
    if not songs or len(set(songs.values())) != len(songs) or max(songs.values()) != last_song:
        raise SystemExit("TAD song enum map is missing, duplicated, or incomplete")
    item_count = last_song + 1  # common audio plus songs 1..LAST_SONG_ID
    table_size = item_count * 3 + 2
    if len(data) <= data_table_offset + table_size or len(data) > 0xFFFF:
        raise SystemExit("Fate TAD binary is outside the single-offset-domain contract")

    offsets = [
        int.from_bytes(data[data_table_offset + index * 3:data_table_offset + index * 3 + 3], "little")
        for index in range(item_count)
    ]
    footer = int.from_bytes(
        data[data_table_offset + item_count * 3:data_table_offset + item_count * 3 + 2], "little"
    )
    if any(value > 0xFFFF for value in offsets):
        raise SystemExit("Fate TAD data table crosses the supported 16-bit offset domain")
    if offsets != sorted(offsets) or footer != len(data) + ASAR_LOROM_BIAS:
        raise SystemExit("Fate TAD data table offsets are malformed")

    # Poppy rejects an empty incbin. Keep one unreachable zero byte in bank 2
    # when the audio blob fits wholly in bank 1. Same_Tad_BlankSong follows that
    # byte, so its logical offset must describe the actual cross-bank label.
    high_data = data[LOROM_BANK_BYTES:]
    encoded_high_data = high_data or b"\x00"
    blank_offset = len(data) if high_data else LOROM_BANK_BYTES + 1

    text = f"""; Generated by tools/generate_fate_tad_layout.py. Do not hand-edit.
SAME_TAD_AUDIO_DRIVER_OFFSET = ${LOADER_SIZE:04X}
SAME_TAD_AUDIO_DRIVER_SIZE   = ${driver_size:04X}
SAME_TAD_DATA_TABLE_OFFSET   = ${data_table_offset:04X}
SAME_TAD_ASAR_LOROM_BIAS     = ${ASAR_LOROM_BIAS:04X}
SAME_TAD_DATA_ITEM_COUNT     = ${item_count:04X}
SAME_TAD_LAST_SONG           = ${last_song:02X}
SAME_TAD_AUDIO_DATA_SIZE     = ${len(data):04X}
SAME_TAD_BLANK_OFFSET        = ${blank_offset:04X}
SAME_TAD_LOROM_SPLIT         = ${LOROM_BANK_BYTES:04X}
"""
    text += "".join(
        f"SAME_TAD_SONG_{name.upper()} = ${identifier:02X}\n"
        for name, identifier in songs.items()
    )
    bank1 = args.binary.with_name("fate-tad-bank1.bin")
    bank2 = args.binary.with_name("fate-tad-bank2.bin")
    bank1.write_bytes(data[:LOROM_BANK_BYTES])
    bank2.write_bytes(encoded_high_data)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(text, encoding="utf-8", newline="\n")
    print(f"{args.output} ({bank1.name} + {bank2.name})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
