#!/usr/bin/env python3
"""Generate the one active-engine binding included by the SNES host."""

from __future__ import annotations

import argparse
from pathlib import Path


SELECTIONS = {
    "demo": "../engines/demo.pasm",
    "scumm_v5": "../engines/scumm_v5_active.pasm",
}


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--engine", choices=sorted(SELECTIONS), default="demo")
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("runtime/snes/generated/active_engine.inc.pasm"),
    )
    args = parser.parse_args()
    text = (
        "; Generated by tools/generate_snes_engine_selection.py.\n"
        f"; active engine: {args.engine}\n"
        f'.include "{SELECTIONS[args.engine]}"\n'
    )
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(text, encoding="utf-8")
    print(f"{args.output}: {args.engine}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
