#!/usr/bin/env python3
"""Generate the one active-engine binding included by the SNES host."""

from __future__ import annotations

import argparse
from pathlib import Path


SELECTIONS = {
    "demo": "../engines/demo.pasm",
    "m24ra_conformance": "../engines/m24ra_conformance.pasm",
    "m24rb_conformance": "../engines/m24rb_conformance.pasm",
    "mode3_surface_conformance": "../engines/mode3_surface_conformance.pasm",
    "qtma_conformance": "../engines/qtma_conformance.pasm",
    "scumm_v5": "../engines/scumm_v5_active.pasm",
}


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--engine", choices=sorted(SELECTIONS), default="demo")
    parser.add_argument("--scumm-m20", action="store_true")
    parser.add_argument("--scumm-m21", action="store_true")
    parser.add_argument("--scumm-m22", action="store_true")
    parser.add_argument("--scumm-m23a", action="store_true")
    parser.add_argument("--scumm-m23b", action="store_true")
    parser.add_argument("--scumm-m23b-negative", action="store_true")
    parser.add_argument("--scumm-m25a-validator", action="store_true")
    parser.add_argument("--scumm-scenario-fixture", action="store_true")
    parser.add_argument("--scumm-scenario-start-room", type=int, default=49)
    parser.add_argument("--scumm-scenario-source-actor-state", action="store_true")
    parser.add_argument("--scumm-m25-movement", action="store_true")
    parser.add_argument("--scumm-phase6hb", action="store_true")
    parser.add_argument("--scumm-phase6la1d", action="store_true")
    parser.add_argument("--scumm-title-start-room", type=int, default=0)
    parser.add_argument("--scumm-title-target-room", type=int, default=0)
    parser.add_argument("--scumm-room-visual", action="store_true")
    parser.add_argument("--scumm-controller", action="store_true")
    parser.add_argument("--scumm-controller-conformance", action="store_true")
    parser.add_argument("--scumm-controller-fixture", action="store_true")
    parser.add_argument("--scumm-controller-behavior-mask", type=lambda value: int(value, 0), default=7)
    parser.add_argument("--scumm-controller-witness", action="store_true")
    parser.add_argument("--scumm-save-persistence-validator", action="store_true")
    parser.add_argument("--scumm-m23c", action="store_true")
    parser.add_argument("--scumm-m23c-class-control", action="store_true")
    parser.add_argument("--scumm-m23c-sound-control", action="store_true")
    parser.add_argument("--scumm-m23c-class-conformance", action="store_true")
    parser.add_argument("--m24ra", action="store_true")
    parser.add_argument("--m24rb", action="store_true")
    parser.add_argument("--m24rb-phase-delay", type=int, default=125)
    parser.add_argument("--m24rb-local-script", type=int, default=208)
    parser.add_argument("--m24rb-primary-sound", type=int, default=80)
    parser.add_argument("--m24rb-layer-sound", type=int, default=82)
    parser.add_argument("--scumm-m23c-source-room", type=int, default=0)
    parser.add_argument("--scumm-m23c-target-room", type=int, default=0)
    parser.add_argument("--scumm-m23c-global-script", type=int, default=0)
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("runtime/snes/generated/active_engine.inc.pasm"),
    )
    args = parser.parse_args()
    text = (
        "; Generated by tools/generate_snes_engine_selection.py.\n"
        f"; active engine: {args.engine}\n"
        f'.include "{SELECTIONS[args.engine]}"\n'
    )
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(text, encoding="utf-8")
    config = args.output.with_name("build_config.inc.pasm")
    config.write_text(
        "; Generated by tools/generate_snes_engine_selection.py.\n"
        f"SAME_BUILD_SCUMM_M19 = ${1 if args.engine == 'scumm_v5' else 0:02X}\n"
        f"SAME_BUILD_MODE3_SURFACE_CONFORMANCE = ${1 if args.engine == 'mode3_surface_conformance' else 0:02X}\n"
        f"SAME_BUILD_SCUMM_M20 = ${1 if args.engine == 'scumm_v5' and args.scumm_m20 else 0:02X}\n"
        f"SAME_BUILD_SCUMM_M21 = ${1 if args.engine == 'scumm_v5' and args.scumm_m21 else 0:02X}\n"
        f"SAME_BUILD_SCUMM_M22 = ${1 if args.engine == 'scumm_v5' and args.scumm_m22 else 0:02X}\n"
        f"SAME_BUILD_SCUMM_M23A = ${1 if args.engine == 'scumm_v5' and args.scumm_m23a else 0:02X}\n"
        f"SAME_BUILD_SCUMM_ROOM_SERVICE = ${1 if args.engine == 'scumm_v5' and (args.scumm_m23a or args.scumm_controller_conformance) else 0:02X}\n"
        f"SAME_BUILD_SCUMM_M23B = ${1 if args.engine == 'scumm_v5' and args.scumm_m23b else 0:02X}\n"
        f"SAME_BUILD_SCUMM_M23B_NEGATIVE = ${1 if args.engine == 'scumm_v5' and args.scumm_m23b_negative else 0:02X}\n"
        f"SAME_BUILD_SCUMM_PHASE6HB = ${1 if args.engine == 'scumm_v5' and args.scumm_phase6hb else 0:02X}\n"
        f"SAME_BUILD_SCUMM_PHASE6LA1D = ${1 if args.engine == 'scumm_v5' and args.scumm_phase6la1d else 0:02X}\n"
        f"SAME_BUILD_SCUMM_M25A_VALIDATOR = ${1 if args.engine == 'scumm_v5' and args.scumm_m25a_validator else 0:02X}\n"
        f"SAME_BUILD_SCUMM_SCENARIO_FIXTURE = ${1 if args.engine == 'scumm_v5' and args.scumm_scenario_fixture else 0:02X}\n"
        f"SAME_SCUMM_SCENARIO_SOURCE_ACTOR_STATE = ${1 if args.engine == 'scumm_v5' and args.scumm_scenario_source_actor_state else 0:02X}\n"
        f"SAME_BUILD_SCUMM_M25_MOVEMENT = ${1 if args.engine == 'scumm_v5' and args.scumm_m25_movement else 0:02X}\n"
        f"SAME_BUILD_SCUMM_ROOM_VISUAL = ${1 if args.engine == 'scumm_v5' and args.scumm_room_visual else 0:02X}\n"
        f"SAME_BUILD_SCUMM_CONTROLLER = ${1 if args.engine == 'scumm_v5' and (args.scumm_controller or args.scumm_controller_fixture) else 0:02X}\n"
        f"SAME_BUILD_SCUMM_CONTROLLER_CONFORMANCE = ${1 if args.engine == 'scumm_v5' and args.scumm_controller_conformance else 0:02X}\n"
        f"SAME_BUILD_SCUMM_CONTROLLER_FIXTURE = ${1 if args.engine == 'scumm_v5' and args.scumm_controller_fixture else 0:02X}\n"
        f"SAME_SCUMM_CONTROLLER_BEHAVIOR_MASK = ${args.scumm_controller_behavior_mask & 0x07:02X}\n"
        f"SAME_SCUMM_CONTROLLER_WITNESS = ${1 if args.engine == 'scumm_v5' and args.scumm_controller_witness else 0:02X}\n"
        f"SAME_BUILD_SCUMM_SAVE_PERSISTENCE_VALIDATOR = ${1 if args.engine == 'scumm_v5' and args.scumm_save_persistence_validator else 0:02X}\n"
        f"SAME_BUILD_SCUMM_M23C = ${1 if args.engine == 'scumm_v5' and args.scumm_m23c else 0:02X}\n"
        f"SAME_BUILD_SCUMM_M23C_CLASS_CONTROL = ${1 if args.engine == 'scumm_v5' and args.scumm_m23c_class_control else 0:02X}\n"
        f"SAME_BUILD_SCUMM_M23C_SOUND_CONTROL = ${1 if args.engine == 'scumm_v5' and args.scumm_m23c_sound_control else 0:02X}\n"
        f"SAME_BUILD_SCUMM_M23C_CLASS_CONFORMANCE = ${1 if args.engine == 'scumm_v5' and args.scumm_m23c_class_conformance else 0:02X}\n"
        f"SAME_BUILD_M24RA = ${1 if (args.engine == 'm24ra_conformance' and args.m24ra) or (args.m24rb and args.engine in ('m24rb_conformance', 'scumm_v5')) else 0:02X}\n"
        f"SAME_BUILD_M24RB = ${1 if args.m24rb and args.engine in ('m24rb_conformance', 'scumm_v5') else 0:02X}\n"
        f"SAME_M24RB_PHASE_DELAY = ${args.m24rb_phase_delay & 0xffff:04X}\n"
        f"SAME_M24RB_LOCAL_SCRIPT = ${args.m24rb_local_script & 0xff:02X}\n"
        f"SAME_M24RB_PRIMARY_SOUND = ${args.m24rb_primary_sound & 0xff:02X}\n"
        f"SAME_M24RB_LAYER_SOUND = ${args.m24rb_layer_sound & 0xff:02X}\n"
        "SAME_M24RB_LSCR_PREFIX_COMMANDS = $0A\n"
        "SAME_M24RB_NEXT_BLOCKER_SCRIPT = $CA\n"
        f"SCUMM_M23C_SOURCE_ROOM = ${args.scumm_m23c_source_room & 0xff:02X}\n"
        f"SCUMM_M23C_TARGET_ROOM = ${args.scumm_m23c_target_room & 0xff:02X}\n"
        f"SCUMM_M23C_GLOBAL_SCRIPT = ${args.scumm_m23c_global_script & 0xff:02X}\n"
        f"SCUMM_V5_TITLE_START_ROOM = ${args.scumm_title_start_room & 0xff:02X}\n"
        f"SCUMM_V5_TITLE_TARGET_ROOM = ${args.scumm_title_target_room & 0xff:02X}\n"
        f"SCUMM_V5_SCENARIO_START_ROOM = ${args.scumm_scenario_start_room & 0xff:02X}\n",
        encoding="utf-8",
    )
    print(f"{args.output}: {args.engine}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
