#!/usr/bin/env python3
"""Generate one target-owned SNES carrier contract for the production build."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from same.snes_carrier import default_carrier, layout_regions, load_carrier


def hex24(value: int) -> str:
    return f"${value:06X}"


def generate(
    *,
    carrier_name: str,
    save_enabled: bool,
    rom_size_code: int,
    output_dir: Path,
    manifest_path: Path,
) -> dict[str, object]:
    carrier = load_carrier(ROOT, carrier_name, save_enabled=save_enabled)
    if not 0 <= rom_size_code <= 0xFF:
        raise ValueError("ROM size code must fit one byte")
    output_dir.mkdir(parents=True, exist_ok=True)

    constants = [
        "; Generated by tools/generate_snes_carrier.py. Do not hand-edit.",
        f"SAME_CARRIER_ID = ${carrier.carrier_id:02X}",
        f"SAME_CARRIER_IS_SA1_BWRAM = ${1 if carrier.name == 'sa1_bwram' else 0:02X}",
        f"SAME_SAVE_STORAGE_BASE = {hex24(carrier.save_base)}",
        f"SAME_SAVE_STORAGE_SIZE = ${carrier.save_bytes:04X}",
    ]
    if carrier.layout is None:
        constants.extend(
            [
                "SAME_BWRAM_BYTES = $000000",
                "SAME_BWRAM_SAVE_BASE = $000000",
                "SAME_BWRAM_SAVE_SIZE = $0000",
                "SAME_BWRAM_BACKEND_BASE = $000000",
                "SAME_BWRAM_BACKEND_SIZE = $0000",
                "SAME_BWRAM_SURFACE_BASE = $000000",
                "SAME_BWRAM_SURFACE_SIZE = $0000",
                "SAME_BWRAM_TILE_SHADOW_BASE = $000000",
                "SAME_BWRAM_TILE_SHADOW_SIZE = $0000",
                "SAME_BWRAM_CGRAM_SHADOW_BASE = $000000",
                "SAME_BWRAM_CGRAM_SHADOW_SIZE = $0000",
                "SAME_BWRAM_STAGING_BASE = $000000",
                "SAME_BWRAM_STAGING_SIZE = $0000",
            ]
        )
    else:
        layout = carrier.layout
        names = {
            "save_reserved": "SAVE",
            "backend_reserved": "BACKEND",
            "live_surface": "SURFACE",
            "tile_shadow": "TILE_SHADOW",
            "cgram_shadow": "CGRAM_SHADOW",
            "future_staging": "STAGING",
        }
        constants.append(f"SAME_BWRAM_BYTES = ${layout['bwram_bytes']:06X}")
        for record_name, constant_name in names.items():
            record = layout[record_name]
            from same.snes_carrier import parse_address

            constants.append(
                f"SAME_BWRAM_{constant_name}_BASE = {hex24(parse_address(record['address']))}"
            )
            constants.append(f"SAME_BWRAM_{constant_name}_SIZE = ${record['bytes']:04X}")
        constants.extend(
            [
                "SAME_BWRAM_CONTROL_MAGIC = SAME_BWRAM_BACKEND_BASE+$0000",
                "SAME_BWRAM_CONTROL_LAYOUT_VERSION = SAME_BWRAM_BACKEND_BASE+$0004",
                "SAME_BWRAM_CONTROL_CARRIER_ID = SAME_BWRAM_BACKEND_BASE+$0005",
                "SAME_BWRAM_CONTROL_SIZE_LO = SAME_BWRAM_BACKEND_BASE+$0006",
                "SAME_BWRAM_CONTROL_SIZE_HI = SAME_BWRAM_BACKEND_BASE+$0008",
                "SAME_BWRAM_CONTROL_SURFACE_VALID = SAME_BWRAM_BACKEND_BASE+$000A",
                "SAME_BWRAM_CONTROL_TILE_VALID = SAME_BWRAM_BACKEND_BASE+$000B",
                "SAME_BWRAM_CONTROL_CGRAM_VALID = SAME_BWRAM_BACKEND_BASE+$000C",
                "SAME_BWRAM_CONTROL_RESERVED = SAME_BWRAM_BACKEND_BASE+$000D",
                "SAME_BWRAM_CONTROL_PENDING_GENERATION = SAME_BWRAM_BACKEND_BASE+$000E",
                "SAME_BWRAM_CONTROL_COMMITTED_GENERATION = SAME_BWRAM_BACKEND_BASE+$0010",
                "SAME_BWRAM_CONTROL_SIZE = $0012",
            ]
        )
    (output_dir / "carrier_constants.inc.pasm").write_text(
        "\n".join(constants) + "\n", encoding="utf-8"
    )

    if carrier.name == "lorom":
        boot = (
            "; Generated ordinary LoROM carrier boot. Intentionally emits no bytes.\n"
        )
        code = (
            "; Generated ordinary LoROM carrier code. Intentionally emits no bytes.\n"
        )
    else:
        boot = """; Generated reset-held SA-1/BW-RAM carrier initialization call.
; Called while forced blank and interrupts remain disabled.
    jsl Same_Carrier_Boot
"""
        code = """; Generated reset-held SA-1/BW-RAM carrier implementation.
.bank 14
.org $8000
Same_Carrier_Boot:
    sep #$20
    .a8
    lda #$20
    sta $2200 ; CCNT: keep SA-1 reset asserted
    lda #$03
    sta $2228 ; BWPA: protect low 2 KiB
    stz $2226 ; SBWE: enforce BWPA
    stz $2224 ; BMAPS: baseline 8 KiB window
    lda #$53
    sta.l SAME_BWRAM_CONTROL_MAGIC+$00
    lda #$41
    sta.l SAME_BWRAM_CONTROL_MAGIC+$01
    lda #$31
    sta.l SAME_BWRAM_CONTROL_MAGIC+$02
    lda #$43
    sta.l SAME_BWRAM_CONTROL_MAGIC+$03
    lda #$01
    sta.l SAME_BWRAM_CONTROL_LAYOUT_VERSION
    lda #SAME_CARRIER_ID
    sta.l SAME_BWRAM_CONTROL_CARRIER_ID
    lda #$00
    sta.l SAME_BWRAM_CONTROL_SURFACE_VALID
    sta.l SAME_BWRAM_CONTROL_TILE_VALID
    sta.l SAME_BWRAM_CONTROL_CGRAM_VALID
    sta.l SAME_BWRAM_CONTROL_RESERVED
    rep #$20
    .a16
    lda #$0000
    sta.l SAME_BWRAM_CONTROL_SIZE_LO
    sta.l SAME_BWRAM_CONTROL_PENDING_GENERATION
    sta.l SAME_BWRAM_CONTROL_COMMITTED_GENERATION
    lda #$0002
    sta.l SAME_BWRAM_CONTROL_SIZE_HI
    sep #$20
    .a8
    rtl
"""
    (output_dir / "carrier_boot.inc.pasm").write_text(boot, encoding="utf-8")
    (output_dir / "carrier_code.inc.pasm").write_text(code, encoding="utf-8")

    header = (
        "; Generated carrier-owned internal-header fields.\n"
        f".byte ${carrier.map_mode:02X}\n"
        f".byte ${carrier.cartridge_type:02X}\n"
        f".byte ${rom_size_code:02X}\n"
        f".byte ${carrier.ram_size:02X}\n"
    )
    (output_dir / "carrier_header.inc.pasm").write_text(header, encoding="utf-8")

    manifest: dict[str, object] = {
        "format": "same-snes-carrier-manifest",
        "version": 1,
        "carrier": carrier.name,
        "carrier_id": carrier.carrier_id,
        "default_carrier": default_carrier(ROOT),
        "save_enabled": save_enabled,
        "header": {
            "map_mode": carrier.map_mode,
            "cartridge_type": carrier.cartridge_type,
            "rom_size": rom_size_code,
            "ram_size": carrier.ram_size,
        },
        "save": {"base": f"{carrier.save_base:06X}", "bytes": carrier.save_bytes},
        "carrier_config_sha256": carrier.config_sha256,
        "layout_sha256": carrier.layout_sha256,
        "layout": carrier.layout,
    }
    if carrier.layout is not None:
        manifest["regions"] = [
            {"name": region.name, "address": f"{region.address:06X}", "bytes": region.size}
            for region in layout_regions(carrier.layout)
        ]
    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    manifest_path.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return manifest


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--carrier", choices=("lorom", "sa1_bwram"), default=None)
    parser.add_argument("--save-enabled", action="store_true")
    parser.add_argument("--rom-size-code", type=lambda value: int(value, 0), required=True)
    parser.add_argument("--output-dir", type=Path, default=ROOT / "runtime/snes/generated")
    parser.add_argument("--manifest", type=Path, required=True)
    args = parser.parse_args()
    carrier = args.carrier or default_carrier(ROOT)
    manifest = generate(
        carrier_name=carrier,
        save_enabled=args.save_enabled,
        rom_size_code=args.rom_size_code,
        output_dir=args.output_dir,
        manifest_path=args.manifest,
    )
    print(json.dumps(manifest, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
