#!/usr/bin/env python3
"""Generate profile/catalog identity bytes for the narrow SNES save backend."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import re


ID_RE = re.compile(r"[a-z0-9][a-z0-9_.-]{0,31}$")


def byte_rows(label: str, data: bytes) -> str:
    rows = [f"{label}:"]
    for offset in range(0, len(data), 16):
        rows.append("    .byte " + ",".join(f"${value:02X}" for value in data[offset:offset + 16]))
    return "\n".join(rows)


def identifier(value: object, field: str) -> bytes:
    if not isinstance(value, str) or ID_RE.fullmatch(value) is None:
        raise RuntimeError(f"{field} is not a valid SAME identifier: {value!r}")
    return value.encode("ascii").ljust(32, b"\0")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--profile", type=Path, required=True)
    parser.add_argument("--catalog", type=Path, required=True)
    parser.add_argument("--logical-id", type=int, default=154)
    parser.add_argument("--sections", type=Path)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()

    profile = json.loads(args.profile.read_text(encoding="utf-8"))
    catalog_raw = args.catalog.read_bytes()
    catalog = json.loads(catalog_raw)
    entries = catalog.get("entries")
    if not isinstance(entries, list):
        raise RuntimeError("compiled-music catalog has no entries array")
    matches = [entry for entry in entries if entry.get("logical_id") == args.logical_id]
    if not matches:
        raise RuntimeError(f"catalog contains no logical sound {args.logical_id}")
    source_hashes = {entry.get("source_sha256") for entry in matches}
    if len(source_hashes) != 1:
        raise RuntimeError("compiled routes do not share one source identity")
    source_sha = matches[0].get("source_sha256")
    if not isinstance(source_sha, str) or re.fullmatch(r"[0-9a-f]{64}", source_sha) is None:
        raise RuntimeError("compiled-music source SHA-256 is absent or malformed")

    engine_id = identifier(profile.get("engine"), "engine id")
    game = profile.get("game")
    if not isinstance(game, dict):
        raise RuntimeError("profile game object is absent")
    game_id = identifier(game.get("id"), "game id")
    catalog_sha = hashlib.sha256(catalog_raw).digest()
    text = (
        "; Generated by tools/generate_snes_save_identity.py. Do not hand-edit.\n"
        f"; logical sound: {args.logical_id}\n"
        f"; catalog SHA-256: {catalog_sha.hex()}\n"
        f"; source SHA-256: {source_sha}\n"
        + byte_rows("Same_Save_EngineIdentity", engine_id) + "\n"
        + byte_rows("Same_Save_GameIdentity", game_id) + "\n"
        + byte_rows("Same_Save_CatalogIdentity", catalog_sha) + "\n"
        + byte_rows("Same_Save_SourceIdentity", bytes.fromhex(source_sha)) + "\n"
    )
    if len(matches) > 1:
        routes = []
        for entry in matches:
            route = entry.get("route")
            if not isinstance(route, dict):
                raise RuntimeError("multi-route save entry has no route identity")
            kind = {"default": 0, "hook": 1}.get(route.get("kind"))
            value, identity = route.get("value"), route.get("identity")
            if (kind is None or isinstance(value, bool) or not isinstance(value, int)
                    or not 0 <= value <= 255 or not isinstance(identity, str)
                    or re.fullmatch(r"[0-9a-f]{64}", identity) is None):
                raise RuntimeError("multi-route save identity is malformed")
            routes.append((kind, value, bytes.fromhex(identity)))
        routes.sort(key=lambda item: (item[0], item[1]))
        text += (
            f"SAME_SAVE_LOGICAL_SOUND = ${args.logical_id:02X}\n"
            f"SAME_SAVE_ROUTE_COUNT = ${len(routes):02X}\n"
            + byte_rows("Same_Save_RouteKinds", bytes(item[0] for item in routes)) + "\n"
            + byte_rows("Same_Save_RouteValues", bytes(item[1] for item in routes)) + "\n"
            + byte_rows("Same_Save_RouteIdentities", b"".join(item[2] for item in routes)) + "\n"
        )
    if args.sections is not None:
        sections = json.loads(args.sections.read_text(encoding="utf-8"))
        if sections.get("schema") != "same_fate_sound80_m22_sections_v1":
            raise RuntimeError("compiled-section identity schema differs")
        plan = sections.get("section_plan_identity")
        bank = sections.get("instrument_bank_sha256")
        if not all(isinstance(value, str) and re.fullmatch(r"[0-9a-f]{64}", value)
                   for value in (plan, bank)):
            raise RuntimeError("compiled-section or instrument-bank identity is malformed")
        history_material = json.dumps(
            sections["cue_route_history"], sort_keys=True, separators=(",", ":"),
        ).encode()
        text += (
            f"SAME_SAVE_SECTION_ROUTE_KIND = $01\n"
            f"SAME_SAVE_SECTION_ROUTE_VALUE = ${int(sections['cue_route_history']['value']):02X}\n"
            f"SAME_SAVE_SECTION_HOOK_VALUE = $08\n"
            f"SAME_SAVE_SECTION_BOUNDARY_TOKEN = ${int(sections['boundary']['token']):02X}\n"
            + byte_rows("Same_Save_SectionPlanIdentity", bytes.fromhex(plan)) + "\n"
            + byte_rows("Same_Save_InstrumentBankIdentity", bytes.fromhex(bank)) + "\n"
            + byte_rows("Same_Save_RouteHistoryIdentity",
                        hashlib.sha256(history_material).digest()) + "\n"
        )
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(text, encoding="utf-8", newline="\n")
    print(args.output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
