#!/usr/bin/env python3
"""Generate the selected production SNES video-backend contract."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from same.snes_carrier import load_carrier, parse_address
from same.snes_video_backend import (
    default_video_backend,
    load_video_backend,
    mode3_static_tilemap,
    validate_mode3_layout,
)


def _hex24(value: int) -> str:
    return f"${value:06X}"


def generate(
    *,
    backend_name: str,
    carrier_name: str,
    output_dir: Path,
    manifest_path: Path,
) -> dict[str, object]:
    backend = load_video_backend(ROOT, backend_name, carrier=carrier_name)
    output_dir.mkdir(parents=True, exist_ok=True)
    constants = [
        "; Generated by tools/generate_snes_video_backend.py. Do not hand-edit.",
        f"SAME_VIDEO_BACKEND_ID = ${backend.backend_id:02X}",
        f"SAME_VIDEO_BACKEND_LEGACY = ${1 if backend.name == 'legacy_backdrop' else 0:02X}",
        f"SAME_VIDEO_BACKEND_MODE3 = ${1 if backend.name == 'mode3_surface' else 0:02X}",
    ]
    if backend.layout is None:
        constants.extend(
            [
                "SAME_VIDEO_ACTIVE_CONVERT_TILE_BUDGET = $0000",
                "SAME_MODE3_LIVE_PALETTE = $000000",
                "SAME_MODE3_CANDIDATE_TILES = $000000",
                "SAME_MODE3_PENDING_TILES = $000000",
                "SAME_MODE3_INFLIGHT_TILES = $000000",
                "SAME_MODE3_CANDIDATE_PALETTE = $000000",
                "SAME_MODE3_PENDING_PALETTE = $000000",
                "SAME_MODE3_INFLIGHT_PALETTE = $000000",
                "SAME_MODE3_TILE_SCRATCH = $000000",
                "SAME_MODE3_INFLIGHT_RECORDS = $000000",
                "SAME_MODE3_WORK = $000000",
                "SAME_MODE3_FIXTURE = $000000",
            ]
        )
    else:
        layout = backend.layout
        validate_mode3_layout(layout)
        carrier = load_carrier(ROOT, carrier_name, save_enabled=False)
        assert carrier.layout is not None
        constants.append(
            f"SAME_VIDEO_ACTIVE_CONVERT_TILE_BUDGET = ${layout['active_convert_tile_budget']:04X}"
        )
        names = {
            "live_palette": "LIVE_PALETTE",
            "candidate_tiles": "CANDIDATE_TILES",
            "pending_tiles": "PENDING_TILES",
            "inflight_tiles": "INFLIGHT_TILES",
            "candidate_palette": "CANDIDATE_PALETTE",
            "pending_palette": "PENDING_PALETTE",
            "inflight_palette": "INFLIGHT_PALETTE",
            "tile_scratch": "TILE_SCRATCH",
            "inflight_records": "INFLIGHT_RECORDS",
            "work": "WORK",
            "fixture": "FIXTURE",
        }
        for key, suffix in names.items():
            constants.append(f"SAME_MODE3_{suffix} = {_hex24(parse_address(layout[key]['address']))}")
            constants.append(f"SAME_MODE3_{suffix}_SIZE = ${layout[key]['bytes']:04X}")
        constants.extend(
            [
                f"SAME_BWRAM_TILE_SHADOW_BASE_LO = ${parse_address(carrier.layout['tile_shadow']['address']) & 0xFFFF:04X}",
                f"SAME_BWRAM_CGRAM_SHADOW_BASE_LO = ${parse_address(carrier.layout['cgram_shadow']['address']) & 0xFFFF:04X}",
                "SAME_MODE3_STATE_UNINITIALIZED = $00",
                "SAME_MODE3_STATE_IDLE = $01",
                "SAME_MODE3_STATE_CONVERTING = $02",
                "SAME_MODE3_STATE_QUEUEING = $03",
                "SAME_MODE3_STATE_WAITING_DMA = $04",
                "SAME_MODE3_STATE_COMPLETE = $05",
                "SAME_MODE3_STATE_ERROR = $FF",
                "SAME_MODE3_CONTROL_BACKEND_ID = SAME_BWRAM_BACKEND_BASE+$0012",
                "SAME_MODE3_CONTROL_STATE = SAME_BWRAM_BACKEND_BASE+$0013",
                "SAME_MODE3_CONTROL_SURFACE_LOCKED = SAME_BWRAM_BACKEND_BASE+$0014",
                "SAME_MODE3_CONTROL_LAST_STATUS = SAME_BWRAM_BACKEND_BASE+$0015",
                "SAME_MODE3_CONTROL_PENDING_GENERATION_HI = SAME_BWRAM_BACKEND_BASE+$0016",
                "SAME_MODE3_CONTROL_COMMITTED_GENERATION_HI = SAME_BWRAM_BACKEND_BASE+$0018",
                "SAME_MODE3_CONTROL_ACCEPTED_PRESENT = SAME_BWRAM_BACKEND_BASE+$001A",
                "SAME_MODE3_CONTROL_REJECTED_PRESENT = SAME_BWRAM_BACKEND_BASE+$001C",
                "SAME_MODE3_CONTROL_REJECTED_DIRTY = SAME_BWRAM_BACKEND_BASE+$001E",
                "SAME_MODE3_CONTROL_REJECTED_PALETTE = SAME_BWRAM_BACKEND_BASE+$0020",
                "SAME_MODE3_CONTROL_CANDIDATE_COUNT = SAME_BWRAM_BACKEND_BASE+$0022",
                "SAME_MODE3_CONTROL_PENDING_COUNT = SAME_BWRAM_BACKEND_BASE+$0024",
                "SAME_MODE3_CONTROL_INFLIGHT_COUNT = SAME_BWRAM_BACKEND_BASE+$0026",
                "SAME_MODE3_CONTROL_EXPECTED_DMA = SAME_BWRAM_BACKEND_BASE+$0028",
                "SAME_MODE3_CONTROL_CONVERTED_COUNT = SAME_BWRAM_BACKEND_BASE+$002A",
                "SAME_MODE3_CONTROL_UNCHANGED_COUNT = SAME_BWRAM_BACKEND_BASE+$002C",
                "SAME_MODE3_CONTROL_QUEUED_TILE_BYTES = SAME_BWRAM_BACKEND_BASE+$002E",
                "SAME_MODE3_CONTROL_QUEUED_CGRAM_BYTES = SAME_BWRAM_BACKEND_BASE+$0030",
                "SAME_MODE3_CONTROL_BATCH_COUNT = SAME_BWRAM_BACKEND_BASE+$0032",
                "SAME_MODE3_CONTROL_RETRY_COUNT = SAME_BWRAM_BACKEND_BASE+$0034",
                "SAME_MODE3_CONTROL_LAST_ERROR = SAME_BWRAM_BACKEND_BASE+$0036",
                "SAME_MODE3_CONTROL_SCAN_TILE = SAME_BWRAM_BACKEND_BASE+$0038",
                "SAME_MODE3_CONTROL_SCAN_PALETTE = SAME_BWRAM_BACKEND_BASE+$003A",
                "SAME_MODE3_CONTROL_BATCH_BYTES = SAME_BWRAM_BACKEND_BASE+$003C",
                "SAME_MODE3_CONTROL_RECORD_COUNT = SAME_BWRAM_BACKEND_BASE+$003E",
                "SAME_MODE3_CONTROL_SIZE = $0040",
                "SAME_MODE3_WORK_TILE = SAME_MODE3_WORK+$0000",
                "SAME_MODE3_WORK_SOURCE = SAME_MODE3_WORK+$0002",
                "SAME_MODE3_WORK_ROW = SAME_MODE3_WORK+$0004",
                "SAME_MODE3_WORK_COLUMN = SAME_MODE3_WORK+$0006",
                "SAME_MODE3_WORK_PIXEL = SAME_MODE3_WORK+$0008",
                "SAME_MODE3_WORK_MASK = SAME_MODE3_WORK+$0009",
                "SAME_MODE3_WORK_BITMASK = SAME_MODE3_WORK+$000A",
                "SAME_MODE3_WORK_CHANGED = SAME_MODE3_WORK+$000B",
                "SAME_MODE3_WORK_INDEX = SAME_MODE3_WORK+$000C",
                "SAME_MODE3_WORK_LIMIT = SAME_MODE3_WORK+$000E",
                "SAME_MODE3_WORK_RUN_START = SAME_MODE3_WORK+$0010",
                "SAME_MODE3_WORK_RUN_COUNT = SAME_MODE3_WORK+$0012",
                "SAME_MODE3_WORK_DESC_TYPE = SAME_MODE3_WORK+$0014",
                "SAME_MODE3_WORK_TEMP = SAME_MODE3_WORK+$0016",
                "SAME_MODE3_WORK_X0 = SAME_MODE3_WORK+$0018",
                "SAME_MODE3_WORK_Y0 = SAME_MODE3_WORK+$001A",
                "SAME_MODE3_WORK_X1 = SAME_MODE3_WORK+$001C",
                "SAME_MODE3_WORK_Y1 = SAME_MODE3_WORK+$001E",
                "SAME_MODE3_WORK_PALETTE_WORD = SAME_MODE3_WORK+$0020",
                "SAME_MODE3_WORK_TIMEOUT = SAME_MODE3_WORK+$0022",
                "SAME_MODE3_INFLIGHT_RECORD_SIZE = $000C",
                "SAME_MODE3_INFLIGHT_TYPE = $00",
                "SAME_MODE3_INFLIGHT_FIRST = $02",
                "SAME_MODE3_INFLIGHT_COUNT = $04",
                "SAME_MODE3_INFLIGHT_BYTES = $06",
                "SAME_MODE3_INFLIGHT_EXPECTED = $08",
                "SAME_MODE3_INFLIGHT_RESERVED = $0A",
                "SAME_MODE3_INFLIGHT_TYPE_TILE = $00",
                "SAME_MODE3_INFLIGHT_TYPE_PALETTE = $02",
                "SAME_MODE3_TILE_COUNT = $0380",
                "SAME_MODE3_TILE_BITSET_BYTES = $0070",
                "SAME_MODE3_PALETTE_COUNT = $0100",
                "SAME_MODE3_PALETTE_BITSET_BYTES = $0020",
                "SAME_MODE3_FIXTURE_PHASE = SAME_MODE3_FIXTURE+$0000",
                "SAME_MODE3_FIXTURE_ROW = SAME_MODE3_FIXTURE+$0002",
                "SAME_MODE3_FIXTURE_TEMP = SAME_MODE3_FIXTURE+$0004",
                "SAME_MODE3_FIXTURE_DONE = SAME_MODE3_FIXTURE+$0006",
            ]
        )
    (output_dir / "video_backend_constants.inc.pasm").write_text(
        "\n".join(constants) + "\n", encoding="utf-8"
    )

    if backend.name == "legacy_backdrop":
        hooks = {
            "boot": "; Legacy video boot hook intentionally emits no bytes.\n",
            "frame": "; Legacy video frame hook intentionally emits no bytes.\n",
            "reset": "; Legacy video reset hook intentionally emits no bytes.\n",
            "service": "; Legacy video service hook intentionally emits no bytes.\n",
            "commit": "; Legacy video commit hook intentionally emits no bytes.\n",
            "code": "; Legacy video backend contributes no code.\n",
        }
    else:
        hooks = {
            "boot": "    jsl Same_Mode3_Boot_Realize_Far\n",
            "frame": "    jsl Same_Mode3_Step_Far\n",
            "reset": "    jsl Same_Mode3_Reset_Far\n",
            "service": "    jsl Same_Mode3_Handle_Far\n    plp\n    rts\n",
            "commit": (
                "    jsr Same_Dma_ProcessQueue\n"
                '.include "video_overlay_commit.inc.pasm"\n'
                "    plp\n"
                "    rts\n"
            ),
            "code": '.include "../services/video_mode3.pasm"\n',
        }
    for name, body in hooks.items():
        (output_dir / f"video_backend_{name}.inc.pasm").write_text(
            "; Generated by tools/generate_snes_video_backend.py.\n" + body,
            encoding="utf-8",
        )
    tilemap_path = output_dir / "video_backend_mode3_tilemap.bin"
    tilemap_path.write_bytes(mode3_static_tilemap() if backend.layout is not None else b"")
    manifest: dict[str, object] = {
        "format": "same-snes-video-backend-manifest",
        "version": 1,
        "backend": backend.name,
        "backend_id": backend.backend_id,
        "default_backend": default_video_backend(ROOT),
        "carrier": carrier_name,
        "required_carrier": backend.required_carrier,
        "backend_config_sha256": backend.config_sha256,
        "layout_sha256": backend.layout_sha256,
        "layout": backend.layout,
        "tilemap_sha256": hashlib.sha256(tilemap_path.read_bytes()).hexdigest(),
    }
    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    manifest_path.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return manifest


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--backend", choices=("legacy_backdrop", "mode3_surface"))
    parser.add_argument("--carrier", choices=("lorom", "sa1_bwram"), required=True)
    parser.add_argument("--output-dir", type=Path, default=ROOT / "runtime/snes/generated")
    parser.add_argument("--manifest", type=Path, required=True)
    args = parser.parse_args()
    result = generate(
        backend_name=args.backend or default_video_backend(ROOT),
        carrier_name=args.carrier,
        output_dir=args.output_dir,
        manifest_path=args.manifest,
    )
    print(json.dumps(result, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
